### ISSUE TITLE
score is same for past 3 months

### ISSUE THREAD

**Issue by arangates** [benbraou/is-angular-ivy-ready#13]
for the past 3 months the score stays at 93.46%

**Comment by atiris** [comment]
Unfortunately, I am afraid this is not the fault of this app. If you look at the data source of this app (official [status for IVY on github](<https://github.com/angular/angular/blob/master/packages/core/src/render3/STATUS.md>)) you see that nothing really has changed.

Even worse, if you look upcomming [ng-conf 2019 schedule](<https://www.ng-conf.org/schedule/>), there is no mention about ivy. There are also no workshop about dynamic templates (from my perspective the most expected feature of angular which ivy should allow and most developers waiting for from Angular 4).

I don't know why this is so, but this is unfortunately the present state. Of course, Ivy is still evolving, but maybe dynamic templates will never be officially possible in Angular (since the beginning of ivy development - more than year ago, I have seen no official example of how ivy programmers expect to use a dynamically loaded templates using ivy and there is still no official ivy documentation).

Do you know if dynamic templates is possible using vue?

**Comment by benbraou** [comment]
Thanks @atiris @arangates 
`ivy` is used by default since version 9. I ll update the app to show that. Sorry for the delay, I was away from Github for a while
